### ISSUE TITLE
Undefined links on platform tabs, downloads, homepage

### ISSUE THREAD

**Issue by benaltair** [blokadaorg/landing#1]
![image](https://user-images.githubusercontent.com/17771229/99716044-77312780-2a5c-11eb-8966-3f71fa0038ed.png)

On https://blokada.org/ there are tabs for **Android**, **iOS**, and **Other**. Only the **Android** tab works. The other two aren't linked correctly. The code on the static page is: `<a data-toggle="tab" role="tab" href="#undefined" class="nav-link">`

As you can see, the anchor link for changing the tab is missing, with `href="#undefined"` instead.

**Comment by kar** [comment]
Fixed, thanks!
